version: 0.0
os: linux

files:
  - source: ./
    destination: /opt/apps

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ec2-user
