package com.seeka.app.util;

public class IConstant {

    public static final String CORRELATION_ID = "correlationId";
    public static final String USER_ID = "userId";
    public static final String SESSION_ID = "sessionId";
    public static final String TENANT_CODE = "tenantCode";
    public static final String SUCCESS_MESSAGE = "Success.!";
    public static final String CATEGORY_GET_SUCCESS = "Category get successfully";
    public static final String CATEGORY_NOT_FOUND = "Category not found";
    public static final String CATEGORY_DELETE_SUCCESS = "Category deleted successfully";
    public static final int SUCCESS_CODE = 1;
    public static final String SUB_CATEGORY_NOT_FOUND = "Sub category not found";
    public static final String INSTITUDE_NOT_FOUND = "Institude is not found";
    public static final String FACULTY_NOT_FOUND = "Faulty is not found";
    public static final String COURSES_NOT_FOUND = "Courses is not found";
    public static final String SUCCESS = "Success.!";
    public static final String FAIL = "Fail.!";
    public static final String DELETE_FAILURE = "Getting issue when article is deleting";
    public static final String DELETE_FAILURE_ID_NOT_FOUND = "Specified article not found";
    public static final String DELETE_SUCCESS = "SeekaArticles deleted successfully";
    public static final String SUB_CATEGORY_ERROR = "Getting datbase transaction error";
    public static final String BASE_PACKAGE = "com.seeka";
    public static final String INSTITUDE_API = "Api Document";
    public static final String COUNTRY_SUCCESS_MESSAGE = "Country addded successfully";
    public static final String CITY_SUCCESS_MESSAGE = "City addded successfully";
    public static final String SCHOLARSHIP_SUCCESS_MESSAGE = "Scholarship addded successfully";
    public static final String SCHOLARSHIP_DELETE_SUCCESS = "Scholarship deleted successfully";
    public static final String DELETE_FAILURE_ID_NOT_FOUND_SCHOLARSHIP = "Specified Scholarship not found";
    public static final String DELETE_FAILURE_SCHOLARSHIP = "Getting issue when Scholarship is deleting";

    public static final String UPDATE_FAILURE_ID_NOT_FOUND_SCHOLARSHIP = "Specified Scholarship not found";
    public static final String UPDATE_FAILURE_SCHOLARSHIP = "Getting issue when Scholarship is updating";
    public static final String SCHOLARSHIP_UPDATE_SUCCESS = "Scholarship updated successfully";
    public static final String EDUCATION_SUCCESS = "Education system get Successfully";
    public static final String EDUCATION_NOT_FOUND = "Education system not found";
    public static final String SQL_ERROR = "Getting sql error";
    public static final String COUNTY_NOT_FOUND = "Country id can't be null";
    public static final String EDUCATION_SUCCESS_UPDATE = "Education system updated successfully";
    public static final String EDUCATION_SYSTEM_NOT_FOUND = "Education system not found";
    public static final String ARTICLE_NOT_FOUND = "Article not found";
    public static final String ARTICLE_GET_SUCCESS = "Article get successfully";
    public static final String ARTICLE_ADD_SUCCESS = "Article added successfully";
    public static final String UPDATE_ARTICLE_FOLDER_SUCCESS = "Article folder updated successfully";
    public static final String ADD_ARTICLE_FOLDER_SUCCESS = "Article folder added successfully";
    public static final String GET_ARTICLE_FOLDER_SUCCESS = "Get article successfully";
    public static final String GET_ARTICLE_FOLDER_NOT_FOUND = "Article not found";
    public static final String ARTICLE_FOLDER_DELETED = "Article folder deleted successfully";
    public static final String FOLDER_ARTICLE_MAP_SUCCESS = "Folder mapped with article successfully";
    public static final String CITY_GET_SUCCESS = "City get successfully";
    public static final String CITY_GET_NOT_FOUND = "City not found";
    public static final String COUNTRY_GET_SUCCESS = "Country get successfully";
    public static final String COUNTRY_GET_NOT_FOUND = "Country not found";
    public static final String DISCOVER_GET_COUNTRY_SUCCESS = "Discover country get successfully";
    public static final String DISCOVER_COUNTRY_NOT_FOUND = "Discover country not found";
    public static final String COURSE_ADD_SUCCESS = "Course added successfully";
    public static final String COURSE_GET_SUCCESS_MESSAGE = "Course get successfully";
    public static final String COURSE_GET_NOT_FOUND = "Course not found";
    public static final String COURSE_DELETED_SUCCESS = "Course deleted successfully";
    public static final String FACULTY_SAVE_SUCCESS = "Faculty added successfully";
}
