package com.seeka.app.bean;import java.math.BigInteger;

// Generated 7 Jun, 2019 2:45:49 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CountryDetails generated by hbm2java
 */
@Entity
@Table(name = "country_details", catalog = "seeka_dev_v5")
public class CountryDetails implements java.io.Serializable {

	private int id;
	private Country country;
	private String capitalCity;
	private String countryFacts;
	private String shortSkilledIndustry;
	private String intHealthCover;
	private String cntSafetyRating;
	private String visa;
	private String jobProspect;
	private String eduRecognition;
	private String workAndStudyRules;
	private String livingNAcomd;
	private String costOfLiving;
	private String climate;
	private String polHelp;
	private String fireHelp;
	private String ambHelp;
	private String eduRecgLink;
	private String studentVisaLink;
	private String area;
	private String population;
	private String people;
	private String language;
	private String religion;
	private String hog;
	private String gdpPc;
	private String anualGrowth;
	private String inflation;
	private String majorIndus;
	private String majorTrdPartnr;
	private String countryVideo;
	private String gdp;
	private Date createdOn;
	private Date updatedOn;
	private String createdBy;
	private String updatedBy;

	public CountryDetails() {
	}

	public CountryDetails(int id, Country country) {
		this.id = id;
		this.country = country;
	}

	public CountryDetails(int id, Country country, String capitalCity,
			String countryFacts, String shortSkilledIndustry,
			String intHealthCover, String cntSafetyRating, String visa,
			String jobProspect, String eduRecognition,
			String workAndStudyRules, String livingNAcomd, String costOfLiving,
			String climate, String polHelp, String fireHelp, String ambHelp,
			String eduRecgLink, String studentVisaLink, String area,
			String population, String people, String language, String religion,
			String hog, String gdpPc, String anualGrowth, String inflation,
			String majorIndus, String majorTrdPartnr, String countryVideo,
			String gdp, Date createdOn, Date updatedOn, String createdBy,
			String updatedBy) {
		this.id = id;
		this.country = country;
		this.capitalCity = capitalCity;
		this.countryFacts = countryFacts;
		this.shortSkilledIndustry = shortSkilledIndustry;
		this.intHealthCover = intHealthCover;
		this.cntSafetyRating = cntSafetyRating;
		this.visa = visa;
		this.jobProspect = jobProspect;
		this.eduRecognition = eduRecognition;
		this.workAndStudyRules = workAndStudyRules;
		this.livingNAcomd = livingNAcomd;
		this.costOfLiving = costOfLiving;
		this.climate = climate;
		this.polHelp = polHelp;
		this.fireHelp = fireHelp;
		this.ambHelp = ambHelp;
		this.eduRecgLink = eduRecgLink;
		this.studentVisaLink = studentVisaLink;
		this.area = area;
		this.population = population;
		this.people = people;
		this.language = language;
		this.religion = religion;
		this.hog = hog;
		this.gdpPc = gdpPc;
		this.anualGrowth = anualGrowth;
		this.inflation = inflation;
		this.majorIndus = majorIndus;
		this.majorTrdPartnr = majorTrdPartnr;
		this.countryVideo = countryVideo;
		this.gdp = gdp;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "country_id", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "capital_city", length = 100)
	public String getCapitalCity() {
		return this.capitalCity;
	}

	public void setCapitalCity(String capitalCity) {
		this.capitalCity = capitalCity;
	}

	@Column(name = "country_facts", length = 100)
	public String getCountryFacts() {
		return this.countryFacts;
	}

	public void setCountryFacts(String countryFacts) {
		this.countryFacts = countryFacts;
	}

	@Column(name = "short_skilled_industry", length = 100)
	public String getShortSkilledIndustry() {
		return this.shortSkilledIndustry;
	}

	public void setShortSkilledIndustry(String shortSkilledIndustry) {
		this.shortSkilledIndustry = shortSkilledIndustry;
	}

	@Column(name = "int_health_cover", length = 100)
	public String getIntHealthCover() {
		return this.intHealthCover;
	}

	public void setIntHealthCover(String intHealthCover) {
		this.intHealthCover = intHealthCover;
	}

	@Column(name = "cnt_safety_rating", length = 100)
	public String getCntSafetyRating() {
		return this.cntSafetyRating;
	}

	public void setCntSafetyRating(String cntSafetyRating) {
		this.cntSafetyRating = cntSafetyRating;
	}

	@Column(name = "visa", length = 50)
	public String getVisa() {
		return this.visa;
	}

	public void setVisa(String visa) {
		this.visa = visa;
	}

	@Column(name = "job_prospect", length = 100)
	public String getJobProspect() {
		return this.jobProspect;
	}

	public void setJobProspect(String jobProspect) {
		this.jobProspect = jobProspect;
	}

	@Column(name = "edu_recognition", length = 100)
	public String getEduRecognition() {
		return this.eduRecognition;
	}

	public void setEduRecognition(String eduRecognition) {
		this.eduRecognition = eduRecognition;
	}

	@Column(name = "work_and_study_rules", length = 100)
	public String getWorkAndStudyRules() {
		return this.workAndStudyRules;
	}

	public void setWorkAndStudyRules(String workAndStudyRules) {
		this.workAndStudyRules = workAndStudyRules;
	}

	@Column(name = "living_n_acomd", length = 100)
	public String getLivingNAcomd() {
		return this.livingNAcomd;
	}

	public void setLivingNAcomd(String livingNAcomd) {
		this.livingNAcomd = livingNAcomd;
	}

	@Column(name = "cost_of_living", length = 100)
	public String getCostOfLiving() {
		return this.costOfLiving;
	}

	public void setCostOfLiving(String costOfLiving) {
		this.costOfLiving = costOfLiving;
	}

	@Column(name = "climate", length = 100)
	public String getClimate() {
		return this.climate;
	}

	public void setClimate(String climate) {
		this.climate = climate;
	}

	@Column(name = "pol_help", length = 100)
	public String getPolHelp() {
		return this.polHelp;
	}

	public void setPolHelp(String polHelp) {
		this.polHelp = polHelp;
	}

	@Column(name = "fire_help", length = 100)
	public String getFireHelp() {
		return this.fireHelp;
	}

	public void setFireHelp(String fireHelp) {
		this.fireHelp = fireHelp;
	}

	@Column(name = "amb_help", length = 100)
	public String getAmbHelp() {
		return this.ambHelp;
	}

	public void setAmbHelp(String ambHelp) {
		this.ambHelp = ambHelp;
	}

	@Column(name = "edu_recg_link", length = 100)
	public String getEduRecgLink() {
		return this.eduRecgLink;
	}

	public void setEduRecgLink(String eduRecgLink) {
		this.eduRecgLink = eduRecgLink;
	}

	@Column(name = "student_visa_link", length = 100)
	public String getStudentVisaLink() {
		return this.studentVisaLink;
	}

	public void setStudentVisaLink(String studentVisaLink) {
		this.studentVisaLink = studentVisaLink;
	}

	@Column(name = "area", length = 100)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "population", length = 100)
	public String getPopulation() {
		return this.population;
	}

	public void setPopulation(String population) {
		this.population = population;
	}

	@Column(name = "people", length = 100)
	public String getPeople() {
		return this.people;
	}

	public void setPeople(String people) {
		this.people = people;
	}

	@Column(name = "Language", length = 100)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "religion", length = 100)
	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	@Column(name = "hog", length = 100)
	public String getHog() {
		return this.hog;
	}

	public void setHog(String hog) {
		this.hog = hog;
	}

	@Column(name = "gdp_pc", length = 100)
	public String getGdpPc() {
		return this.gdpPc;
	}

	public void setGdpPc(String gdpPc) {
		this.gdpPc = gdpPc;
	}

	@Column(name = "anual_growth", length = 100)
	public String getAnualGrowth() {
		return this.anualGrowth;
	}

	public void setAnualGrowth(String anualGrowth) {
		this.anualGrowth = anualGrowth;
	}

	@Column(name = "inflation", length = 100)
	public String getInflation() {
		return this.inflation;
	}

	public void setInflation(String inflation) {
		this.inflation = inflation;
	}

	@Column(name = "major_indus", length = 100)
	public String getMajorIndus() {
		return this.majorIndus;
	}

	public void setMajorIndus(String majorIndus) {
		this.majorIndus = majorIndus;
	}

	@Column(name = "major_trd_partnr", length = 100)
	public String getMajorTrdPartnr() {
		return this.majorTrdPartnr;
	}

	public void setMajorTrdPartnr(String majorTrdPartnr) {
		this.majorTrdPartnr = majorTrdPartnr;
	}

	@Column(name = "country_video", length = 100)
	public String getCountryVideo() {
		return this.countryVideo;
	}

	public void setCountryVideo(String countryVideo) {
		this.countryVideo = countryVideo;
	}

	@Column(name = "gdp", length = 100)
	public String getGdp() {
		return this.gdp;
	}

	public void setGdp(String gdp) {
		this.gdp = gdp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
