package com.seeka.app.bean;

import java.io.Serializable;

// Generated 7 Jun, 2019 2:45:49 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course")
@ToString
@EqualsAndHashCode
public class Course implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8492390790670110780L;
	private String id;
	private Faculty faculty;
	private Institute institute;
	private String name;
	private Integer worldRanking;
	private Integer stars;
	private String recognition;
	private String recognitionType;
	private Double duration;
	private String durationTime;
	private String website;
	private String language;
	private String abbreviation;
	private Date recDate;
	private String remarks;
	private String description;
	private Boolean isActive;
	private Date createdOn;
	private Date updatedOn;
	private Date deletedOn;
	private String createdBy;
	private String updatedBy;
	private Boolean isDeleted;
	private Level level;

	private String availbilty;
	private String partFull;
	private String studyMode;
	private String intake;
	private String fileUrl;
	private String grades;
	private String contact;
	private String openingHourFrom;
	private String openingHourTo;
	private String campusLocation;
	private String jobFullTime;
	private String jobPartTime;
	private String link;
	private Double domesticFee;
	private Double internationalFee;
	private String currency;
	private String currencyTime;
	private Double usdInternationFee;
	private Double usdDomasticFee;
	private Double costRange;

	public Course() {
	}

	public Course(final Faculty faculty, final Institute institute, final String name, final Integer worldRanking,
			final Integer stars, final String recognition, final String recognitionType, final Double duration, final String durationTime, final String website,
			final String language, final String abbreviation, final Date recDate, final String remarks, final String description, final Boolean isActive,
			final Date createdOn, final Date updatedOn, final Date deletedOn, final String createdBy, final String updatedBy, final Boolean isDeleted) {
		this.faculty = faculty;
		this.institute = institute;
		this.name = name;
		this.worldRanking = worldRanking;
		this.stars = stars;
		this.recognition = recognition;
		this.recognitionType = recognitionType;
		this.duration = duration;
		this.durationTime = durationTime;
		this.website = website;
		this.language = language;
		this.abbreviation = abbreviation;
		this.recDate = recDate;
		this.remarks = remarks;
		this.description = description;
		this.isActive = isActive;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.deletedOn = deletedOn;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.isDeleted = isDeleted;
	}

	@Id
	@GenericGenerator(name = "generator", strategy = "guid", parameters = {})
	@GeneratedValue(generator = "generator")
	@Column(name = "id", columnDefinition = "uniqueidentifier")
	public String getId() {
		return this.id;
	}

	public void setId(final String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "faculty_id")
	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(final Faculty faculty) {
		this.faculty = faculty;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "institute_id")
	public Institute getInstitute() {
		return this.institute;
	}

	public void setInstitute(final Institute institute) {
		this.institute = institute;
	}

	@Column(name = "name", length = 245)
	public String getName() {
		return this.name;
	}

	public void setName(final String name) {
		this.name = name;
	}

	@Column(name = "world_ranking", length = 50)
	public Integer getWorldRanking() {
		return this.worldRanking;
	}

	public void setWorldRanking(final Integer worldRanking) {
		this.worldRanking = worldRanking;
	}

	@Column(name = "stars", length = 50)
	public Integer getStars() {
		return this.stars;
	}

	public void setStars(final Integer stars) {
		this.stars = stars;
	}

	@Column(name = "recognition", length = 250)
	public String getRecognition() {
		return this.recognition;
	}

	public void setRecognition(final String recognition) {
		this.recognition = recognition;
	}

	@Column(name = "recognition_type", length = 250)
	public String getRecognitionType() {
		return this.recognitionType;
	}

	public void setRecognitionType(final String recognitionType) {
		this.recognitionType = recognitionType;
	}

	@Column(name = "duration", length = 250)
	public Double getDuration() {
		return this.duration;
	}

	public void setDuration(final Double duration) {
		this.duration = duration;
	}

	@Column(name = "duration_time", length = 250)
	public String getDurationTime() {
		return this.durationTime;
	}

	public void setDurationTime(final String durationTime) {
		this.durationTime = durationTime;
	}

	@Column(name = "website", length = 500)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(final String website) {
		this.website = website;
	}

	@Column(name = "language", length = 45)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(final String language) {
		this.language = language;
	}

	@Column(name = "abbreviation", length = 500)
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(final String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_date", length = 19)
	public Date getRecDate() {
		return this.recDate;
	}

	public void setRecDate(final Date recDate) {
		this.recDate = recDate;
	}

	@Column(name = "remarks", length = 500)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(final String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(final String description) {
		this.description = description;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(final Boolean isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(final Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(final Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_on", length = 19)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(final Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(final String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(final String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(final Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * @return the levelCode
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "level_id")

	public Level getLevel() {
		return level;
	}

	public void setLevel(final Level level) {
		this.level = level;
	}

	@Column(name = "availbilty", length = 250)
	public String getAvailbilty() {
		return this.availbilty;
	}

	public void setAvailbilty(final String availbilty) {
		this.availbilty = availbilty;
	}

	@Column(name = "part_full", length = 50)
	public String getPartFull() {
		return this.partFull;
	}

	public void setPartFull(final String partFull) {
		this.partFull = partFull;
	}

	@Column(name = "study_mode", length = 50)
	public String getStudyMode() {
		return this.studyMode;
	}

	public void setStudyMode(final String studyMode) {
		this.studyMode = studyMode;
	}

	@Column(name = "currency", length = 100)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(final String currency) {
		this.currency = currency;
	}

	@Column(name = "currency_time", length = 250)
	public String getCurrencyTime() {
		return this.currencyTime;
	}

	public void setCurrencyTime(final String currencyTime) {
		this.currencyTime = currencyTime;
	}

	/**
	 * @return the usdInternationFee
	 */
	@Column(name = "usd_international_fee")
	public Double getUsdInternationFee() {
		return usdInternationFee;
	}

	/**
	 * @param usdInternationFee the usdInternationFee to set
	 */
	public void setUsdInternationFee(final Double usdInternationFee) {
		this.usdInternationFee = usdInternationFee;
	}

	/**
	 * @return the usdDomasticFee
	 */
	@Column(name = "usd_domestic_fee")
	public Double getUsdDomasticFee() {
		return usdDomasticFee;
	}

	/**
	 * @param usdDomasticFee the usdDomasticFee to set
	 */
	public void setUsdDomasticFee(final Double usdDomasticFee) {
		this.usdDomasticFee = usdDomasticFee;
	}

	/**
	 * @return the intake
	 */
	@Column(name = "intake")
	public String getIntake() {
		return intake;
	}

	/**
	 * @param intake the intake to set
	 */
	public void setIntake(final String intake) {
		this.intake = intake;
	}

	/**
	 * @return the fileUrl
	 */
	@Transient
	public String getFileUrl() {
		return fileUrl;
	}

	/**
	 * @param fileUrl the fileUrl to set
	 */
	public void setFileUrl(final String fileUrl) {
		this.fileUrl = fileUrl;
	}

	/**
	 * @return the grades
	 */
	@Transient
	public String getGrades() {
		return grades;
	}

	/**
	 * @param grades the grades to set
	 */
	public void setGrades(final String grades) {
		this.grades = grades;
	}

	/**
	 * @return the contact
	 */
	@Column(name = "contact")
	public String getContact() {
		return contact;
	}

	/**
	 * @param contact the contact to set
	 */
	public void setContact(final String contact) {
		this.contact = contact;
	}

	@Column(name = "opening_hour_from")
	public String getOpeningHourFrom() {
		return openingHourFrom;
	}

	public void setOpeningHourFrom(final String openingHourFrom) {
		this.openingHourFrom = openingHourFrom;
	}

	@Column(name = "opening_hour_to")
	public String getOpeningHourTo() {
		return openingHourTo;
	}

	public void setOpeningHourTo(final String openingHourTo) {
		this.openingHourTo = openingHourTo;
	}

	/**
	 * @return the campusLocation
	 */
	@Column(name = "campus_location")
	public String getCampusLocation() {
		return campusLocation;
	}

	/**
	 * @param campusLocation the campusLocation to set
	 */
	public void setCampusLocation(final String campusLocation) {
		this.campusLocation = campusLocation;
	}

	/**
	 * @return the jobFullTime
	 */
	@Column(name = "job_full_time")
	public String getJobFullTime() {
		return jobFullTime;
	}

	/**
	 * @param jobFullTime the jobFullTime to set
	 */
	public void setJobFullTime(final String jobFullTime) {
		this.jobFullTime = jobFullTime;
	}

	/**
	 * @return the jobPartTime
	 */
	@Column(name = "job_part_time")
	public String getJobPartTime() {
		return jobPartTime;
	}

	/**
	 * @param jobPartTime the jobPartTime to set
	 */
	public void setJobPartTime(final String jobPartTime) {
		this.jobPartTime = jobPartTime;
	}

	/**
	 * @return the link
	 */
	@Column(name = "link")
	public String getLink() {
		return link;
	}

	/**
	 * @param link the link to set
	 */
	public void setLink(final String link) {
		this.link = link;
	}

	/**
	 * @return the domesticFee
	 */
	@Column(name = "domestic_fee")
	public Double getDomesticFee() {
		return domesticFee;
	}

	/**
	 * @param domesticFee the domesticFee to set
	 */
	public void setDomesticFee(final Double domesticFee) {
		this.domesticFee = domesticFee;
	}

	/**
	 * @return the internationalFee
	 */
	@Column(name = "international_fee")
	public Double getInternationalFee() {
		return internationalFee;
	}

	/**
	 * @param internationalFee the internationalFee to set
	 */
	public void setInternationalFee(final Double internationalFee) {
		this.internationalFee = internationalFee;
	}

	@Column(name = "cost_range", precision = 18, scale = 3)
	public Double getCostRange() {
		return this.costRange;
	}

	public void setCostRange(final Double costRange) {
		this.costRange = costRange;
	}
}