package com.seeka.app.bean;import java.math.BigInteger;

// Generated 7 Jun, 2019 2:45:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourseGradeEligibility generated by hbm2java
 */
@Entity
@Table(name = "course_grade_eligibility", catalog = "seeka_dev_v5")
public class CourseGradeEligibility implements java.io.Serializable {

	private BigInteger courseId;
	private Double globalGpa;
	private String globalALevel1;
	private String globalALevel2;
	private String globalALevel3;
	private String globalALevel4;
	private String globalALevel5;
	private Boolean isActive;
	private Date createdOn;
	private Date updatedOn;
	private Date deletedOn;
	private String createdBy;
	private String updatedBy;
	private Boolean isDeleted;

	public CourseGradeEligibility() {
	}

	public CourseGradeEligibility(Double globalGpa, String globalALevel1,
			String globalALevel2, String globalALevel3, String globalALevel4,
			String globalALevel5, Boolean isActive, Date createdOn,
			Date updatedOn, Date deletedOn, String createdBy, String updatedBy,
			Boolean isDeleted) {
		this.globalGpa = globalGpa;
		this.globalALevel1 = globalALevel1;
		this.globalALevel2 = globalALevel2;
		this.globalALevel3 = globalALevel3;
		this.globalALevel4 = globalALevel4;
		this.globalALevel5 = globalALevel5;
		this.isActive = isActive;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.deletedOn = deletedOn;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.isDeleted = isDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "course_id", unique = true, nullable = false)
	public BigInteger getCourseId() {
		return this.courseId;
	}

	public void setCourseId(BigInteger courseId) {
		this.courseId = courseId;
	}

	@Column(name = "global_gpa", precision = 18)
	public Double getGlobalGpa() {
		return this.globalGpa;
	}

	public void setGlobalGpa(Double globalGpa) {
		this.globalGpa = globalGpa;
	}

	@Column(name = "global_a_level_1", length = 10)
	public String getGlobalALevel1() {
		return this.globalALevel1;
	}

	public void setGlobalALevel1(String globalALevel1) {
		this.globalALevel1 = globalALevel1;
	}

	@Column(name = "global_a_level_2", length = 10)
	public String getGlobalALevel2() {
		return this.globalALevel2;
	}

	public void setGlobalALevel2(String globalALevel2) {
		this.globalALevel2 = globalALevel2;
	}

	@Column(name = "global_a_level_3", length = 10)
	public String getGlobalALevel3() {
		return this.globalALevel3;
	}

	public void setGlobalALevel3(String globalALevel3) {
		this.globalALevel3 = globalALevel3;
	}

	@Column(name = "global_a_level_4", length = 10)
	public String getGlobalALevel4() {
		return this.globalALevel4;
	}

	public void setGlobalALevel4(String globalALevel4) {
		this.globalALevel4 = globalALevel4;
	}

	@Column(name = "global_a_level_5", length = 10)
	public String getGlobalALevel5() {
		return this.globalALevel5;
	}

	public void setGlobalALevel5(String globalALevel5) {
		this.globalALevel5 = globalALevel5;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_on", length = 19)
	public Date getDeletedOn() {
		return this.deletedOn;
	}

	public void setDeletedOn(Date deletedOn) {
		this.deletedOn = deletedOn;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
