package com.seeka.app.bean;import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigInteger;

// Generated 7 Jun, 2019 2:45:49 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CourseDetails generated by hbm2java
 */
@Entity
@Table(name = "course_details", catalog = "seeka_dev_v5")
public class CourseDetails implements java.io.Serializable {

	private BigInteger id;
	private Course course;
	private String wrRange;
	private String availbilty;
	private String partFull;
	private String studyMode;
	private String description;
	
    private CoursePricing coursePricingObj;

    private Faculty facultyObj;

    private Level LevelObj;

    private FacultyLevel facultyLevelObj;

    private InstituteLevel instituteLevelObj;

    private CourseGradeEligibility gradeObj;

	public CourseDetails() {
	}

	public CourseDetails(Course course) {
		this.course = course;
	}

	public CourseDetails(Course course, String wrRange, String availbilty,
			String partFull, String studyMode, String description) {
		this.course = course;
		this.wrRange = wrRange;
		this.availbilty = availbilty;
		this.partFull = partFull;
		this.studyMode = studyMode;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public BigInteger getId() {
		return this.id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "course_id", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "wr_range", length = 50)
	public String getWrRange() {
		return this.wrRange;
	}

	public void setWrRange(String wrRange) {
		this.wrRange = wrRange;
	}

	@Column(name = "availbilty", length = 250)
	public String getAvailbilty() {
		return this.availbilty;
	}

	public void setAvailbilty(String availbilty) {
		this.availbilty = availbilty;
	}

	@Column(name = "part_full", length = 50)
	public String getPartFull() {
		return this.partFull;
	}

	public void setPartFull(String partFull) {
		this.partFull = partFull;
	}

	@Column(name = "study_mode", length = 50)
	public String getStudyMode() {
		return this.studyMode;
	}

	public void setStudyMode(String studyMode) {
		this.studyMode = studyMode;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

    /**
     * @return the coursePricingObj
     */
	@Transient
    public CoursePricing getCoursePricingObj() {
        return coursePricingObj;
    }

    /**
     * @param coursePricingObj the coursePricingObj to set
     */
    public void setCoursePricingObj(CoursePricing coursePricingObj) {
        this.coursePricingObj = coursePricingObj;
    }

    /**
     * @return the facultyObj
     */
    @Transient
    public Faculty getFacultyObj() {
        return facultyObj;
    }

    /**
     * @param facultyObj the facultyObj to set
     */
    public void setFacultyObj(Faculty facultyObj) {
        this.facultyObj = facultyObj;
    }

    /**
     * @return the levelObj
     */
    @Transient
    public Level getLevelObj() {
        return LevelObj;
    }

    /**
     * @param levelObj the levelObj to set
     */
    public void setLevelObj(Level levelObj) {
        LevelObj = levelObj;
    }

    /**
     * @return the facultyLevelObj
     */
    @Transient
    public FacultyLevel getFacultyLevelObj() {
        return facultyLevelObj;
    }

    /**
     * @param facultyLevelObj the facultyLevelObj to set
     */
    public void setFacultyLevelObj(FacultyLevel facultyLevelObj) {
        this.facultyLevelObj = facultyLevelObj;
    }

    /**
     * @return the instituteLevelObj
     */
    @Transient
    public InstituteLevel getInstituteLevelObj() {
        return instituteLevelObj;
    }

    /**
     * @param instituteLevelObj the instituteLevelObj to set
     */
    public void setInstituteLevelObj(InstituteLevel instituteLevelObj) {
        this.instituteLevelObj = instituteLevelObj;
    }

    /**
     * @return the gradeObj
     */
    @Transient
    public CourseGradeEligibility getGradeObj() {
        return gradeObj;
    }

    /**
     * @param gradeObj the gradeObj to set
     */
    public void setGradeObj(CourseGradeEligibility gradeObj) {
        this.gradeObj = gradeObj;
    }

}
