package com.seeka.app.bean;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "currency_rate")
public class CurrencyRate implements java.io.Serializable {

	private static final long serialVersionUID = -557774430558637048L;
	
    private String id;
    private String fromCurrencyCode;
    private String toCurrencyCode;
    private Double conversionRate;
    
    // private String rateDetail;
    private Date createdAt;
    private Date updatedAt;
    
    private String fromCurrencyName;
    private String toCurrencyName;
    private Boolean hasChanged;
    
    
	@Id
	@GenericGenerator(name = "generator", strategy = "guid", parameters = {})
	@GeneratedValue(generator = "generator")
	@Column(name = "id", columnDefinition = "uniqueidentifier")
    public String getId() {
        return this.id;
    }

	public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the baseCurrencyId
     */
    @Column(name = "from_currency_code")
    public String getFromCurrencyCode() {
  		return fromCurrencyCode;
  	}

  	public void setFromCurrencyCode(String fromCurrencyCode) {
  		this.fromCurrencyCode = fromCurrencyCode;
  	}

    /**
     * @return the createdDate
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", length = 19)
    public Date getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

    @Column(name = "to_currency_code")
	public String getToCurrencyCode() {
		return toCurrencyCode;
	}

	public void setToCurrencyCode(String toCurrencyCode) {
		this.toCurrencyCode = toCurrencyCode;
	}

	@Column(name = "conversion_rate")
	public Double getConversionRate() {
		return conversionRate;
	}

	public void setConversionRate(Double conversionRate) {
		this.conversionRate = conversionRate;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_date", length = 19)
	public Date getUpdatedAt() {
		return updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "from_currency_name", length = 100)
	public String getFromCurrencyName() {
		return fromCurrencyName;
	}

	public void setFromCurrencyName(String fromCurrencyName) {
		this.fromCurrencyName = fromCurrencyName;
	}

	@Column(name = "to_currency_name", length = 100)
	public String getToCurrencyName() {
		return toCurrencyName;
	}

	public void setToCurrencyName(String toCurrencyName) {
		this.toCurrencyName = toCurrencyName;
	}

	@Column(name="has_changed")
	public Boolean getHasChanged() {
		return hasChanged;
	}

	public void setHasChanged(Boolean hasChanged) {
		this.hasChanged = hasChanged;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CurrencyRate [id=").append(id).append(", fromCurrencyCode=").append(fromCurrencyCode)
				.append(", toCurrencyCode=").append(toCurrencyCode).append(", conversionRate=").append(conversionRate)
				.append(", createdAt=").append(createdAt).append(", updatedAt=").append(updatedAt)
				.append(", fromCurrencyName=").append(fromCurrencyName).append(", toCurrencyName=")
				.append(toCurrencyName).append(", hasChanged=").append(hasChanged).append("]");
		return builder.toString();
	}
}
