package com.seeka.app.bean;

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "currency_rate")
public class CurrencyRate implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -4896547771928499529L;
    private BigInteger id;
    private BigInteger baseCurrencyId;
    private String rateDetail;
    private String createdDate;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * @return the baseCurrencyId
     */
    @Column(name = "base_currency_id")
    public BigInteger getBaseCurrencyId() {
        return baseCurrencyId;
    }

    /**
     * @param baseCurrencyId
     *            the baseCurrencyId to set
     */
    public void setBaseCurrencyId(BigInteger baseCurrencyId) {
        this.baseCurrencyId = baseCurrencyId;
    }

    /**
     * @return the rateDetail
     */
    @Column(name = "rate_detail")
    public String getRateDetail() {
        return rateDetail;
    }

    /**
     * @param rateDetail
     *            the rateDetail to set
     */
    public void setRateDetail(String rateDetail) {
        this.rateDetail = rateDetail;
    }

    /**
     * @return the createdDate
     */
    @Column(name = "created_date")
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * @param createdDate
     *            the createdDate to set
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

}
