package com.seeka.app.bean;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Currency generated by hbm2java
 */
@Entity
@Table(name = "education_agent_accomplishment")
public class EducationAgentAccomplishment implements Serializable {

    private static final long serialVersionUID = 5111616897386950348L;
    private BigInteger id;
    private String accomplishment;
    private EducationAgent educationAgent;

    public EducationAgentAccomplishment() {
        super();
        // TODO Auto-generated constructor stub
    }

    public EducationAgentAccomplishment(BigInteger id, String accomplishment, EducationAgent educationAgent) {
        super();
        this.id = id;
        this.accomplishment = accomplishment;
        this.educationAgent = educationAgent;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public BigInteger getId() {
        return id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    @Column(name = "accomplishment", length = 50)
    public String getAccomplishment() {
        return accomplishment;
    }

    public void setAccomplishment(String accomplishment) {
        this.accomplishment = accomplishment;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "education_agent")
    public EducationAgent getEducationAgent() {
        return educationAgent;
    }

    public void setEducationAgent(EducationAgent educationAgent) {
        this.educationAgent = educationAgent;
    }

}
