package com.seeka.app.bean;

import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "grade_details")
public class GradeDetails implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private String id;
    private BigInteger countryId;
    private BigInteger educationSystemId;
    private String grade;
    private String gpaGrade;
    private Date createdOn;
    private Date updatedOn;
    private String createdBy;
    private String updatedBy;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Column(name = "created_by", length = 50)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "updated_by", length = 50)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * @return the id
     */
    @Id
    @GenericGenerator(name = "generator", strategy = "guid", parameters = {})
	@GeneratedValue(generator = "generator")
	@Column(name = "id", columnDefinition = "uniqueidentifier")
    public String getId() {
        return id;
    }

    /**
     * @param id
     *            the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the countryId
     */
    @Column(name = "country_id")
    public BigInteger getCountryId() {
        return countryId;
    }

    /**
     * @param countryId
     *            the countryId to set
     */
    public void setCountryId(BigInteger countryId) {
        this.countryId = countryId;
    }

    /**
     * @return the educationSystemId
     */
    @Column(name = "education_system_id")
    public BigInteger getEducationSystemId() {
        return educationSystemId;
    }

    /**
     * @param educationSystemId
     *            the educationSystemId to set
     */
    public void setEducationSystemId(BigInteger educationSystemId) {
        this.educationSystemId = educationSystemId;
    }

    /**
     * @return the grade
     */
    @Column(name = "grade")
    public String getGrade() {
        return grade;
    }

    /**
     * @param grade
     *            the grade to set
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * @return the gpaGrade
     */
    @Column(name = "gpa_grade")
    public String getGpaGrade() {
        return gpaGrade;
    }

    /**
     * @param gpaGrade
     *            the gpaGrade to set
     */
    public void setGpaGrade(String gpaGrade) {
        this.gpaGrade = gpaGrade;
    }
}
