package com.seeka.app.bean;

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigInteger;

// Generated 7 Jun, 2019 2:45:49 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Institute generated by hbm2java
 */
@Entity
@Table(name = "institute", catalog = "seeka_dev_v5")
public class Institute implements java.io.Serializable {

    private BigInteger id;
    private City city;
    private Country country;
    private InstituteType instituteType;
    private String name;
    private Integer worldRanking;
    private String accredited;
    private String intPhNum;
    private String intEmails;
    private String website;
    private Integer insImgCnt;
    private Integer TNumOfStu;
    private String latitude;
    private String longitude;
    private String address;
    private String description;
    private Boolean isActive;
    private Date createdOn;
    private Date updatedOn;
    private Date deletedOn;
    private String createdBy;
    private String updatedBy;
    private Boolean isDeleted;

    private String instituteLogoUrl;

    private String instituteImageUrl;

    private InstituteDetails instituteDetailsObj;

    private List<InstituteService> serviceList;

    public Institute() {
    }

    public Institute(City city, Country country, InstituteType instituteType, String name, Integer worldRanking, String accredited, String intPhNum, String intEmails,
                    String website, Integer insImgCnt, Integer TNumOfStu, String latitude, String longitude, String address, String description, Boolean isActive, Date createdOn,
                    Date updatedOn, Date deletedOn, String createdBy, String updatedBy, Boolean isDeleted) {
        this.city = city;
        this.country = country;
        this.instituteType = instituteType;
        this.name = name;
        this.worldRanking = worldRanking;
        this.accredited = accredited;
        this.intPhNum = intPhNum;
        this.intEmails = intEmails;
        this.website = website;
        this.insImgCnt = insImgCnt;
        this.TNumOfStu = TNumOfStu;
        this.latitude = latitude;
        this.longitude = longitude;
        this.address = address;
        this.description = description;
        this.isActive = isActive;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.deletedOn = deletedOn;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.isDeleted = isDeleted;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "city_id")
    public City getCity() {
        return this.city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "country_id")
    public Country getCountry() {
        return this.country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "institute_type_id")
    public InstituteType getInstituteType() {
        return this.instituteType;
    }

    public void setInstituteType(InstituteType instituteType) {
        this.instituteType = instituteType;
    }

    @Column(name = "name", length = 145)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "world_ranking")
    public Integer getWorldRanking() {
        return this.worldRanking;
    }

    public void setWorldRanking(Integer worldRanking) {
        this.worldRanking = worldRanking;
    }

    @Column(name = "accredited", length = 20)
    public String getAccredited() {
        return this.accredited;
    }

    public void setAccredited(String accredited) {
        this.accredited = accredited;
    }

    @Column(name = "int_ph_num", length = 100)
    public String getIntPhNum() {
        return this.intPhNum;
    }

    public void setIntPhNum(String intPhNum) {
        this.intPhNum = intPhNum;
    }

    @Column(name = "int_emails", length = 250)
    public String getIntEmails() {
        return this.intEmails;
    }

    public void setIntEmails(String intEmails) {
        this.intEmails = intEmails;
    }

    @Column(name = "website", length = 500)
    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    @Column(name = "ins_img_cnt")
    public Integer getInsImgCnt() {
        return this.insImgCnt;
    }

    public void setInsImgCnt(Integer insImgCnt) {
        this.insImgCnt = insImgCnt;
    }

    @Column(name = "t_num_of_stu")
    public Integer getTNumOfStu() {
        return this.TNumOfStu;
    }

    public void setTNumOfStu(Integer TNumOfStu) {
        this.TNumOfStu = TNumOfStu;
    }

    @Column(name = "latitude", length = 100)
    public String getLatitude() {
        return this.latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    @Column(name = "longitude", length = 100)
    public String getLongitude() {
        return this.longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    @Column(name = "address", length = 500)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "description", length = 500)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "deleted_on", length = 19)
    public Date getDeletedOn() {
        return this.deletedOn;
    }

    public void setDeletedOn(Date deletedOn) {
        this.deletedOn = deletedOn;
    }

    @Column(name = "created_by", length = 50)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "updated_by", length = 50)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Column(name = "is_deleted")
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * @return the instituteLogoUrl
     */
    @Transient
    public String getInstituteLogoUrl() {
        return instituteLogoUrl;
    }

    /**
     * @param instituteLogoUrl
     *            the instituteLogoUrl to set
     */
    public void setInstituteLogoUrl(String instituteLogoUrl) {
        this.instituteLogoUrl = instituteLogoUrl;
    }

    /**
     * @return the instituteImageUrl
     */
    @Transient
    public String getInstituteImageUrl() {
        return instituteImageUrl;
    }

    /**
     * @param instituteImageUrl
     *            the instituteImageUrl to set
     */
    public void setInstituteImageUrl(String instituteImageUrl) {
        this.instituteImageUrl = instituteImageUrl;
    }

    /**
     * @return the instituteDetailsObj
     */
    @Transient
    public InstituteDetails getInstituteDetailsObj() {
        return instituteDetailsObj;
    }

    /**
     * @param instituteDetailsObj
     *            the instituteDetailsObj to set
     */
    public void setInstituteDetailsObj(InstituteDetails instituteDetailsObj) {
        this.instituteDetailsObj = instituteDetailsObj;
    }

    /**
     * @return the serviceList
     */
    @Transient
    public List<InstituteService> getServiceList() {
        return serviceList;
    }

    /**
     * @param serviceList
     *            the serviceList to set
     */
    public void setServiceList(List<InstituteService> serviceList) {
        this.serviceList = serviceList;
    }

}
