package com.seeka.app.bean;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.math.BigInteger;

// Generated 7 Jun, 2019 2:45:49 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InstituteDetails generated by hbm2java
 */
@Entity
@Table(name = "institute_details")
public class InstituteDetails implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -973962347894823810L;
    private BigInteger instituteId;
    private String type;
    private String youtubeLink;
    private String ttionFeesPPlan;
    private String courseStart;
    private String openingHour;
    private String closingHour;
    private String enrolmentLink;
    private String aboutUsInfo;
    private String climate2;
    private String avgCostOfLiving;
    private String whatsappNo;
    private String englishPartners;

    private String latitute;
    private String longitude;
    private Integer totalStudent;
    private Integer worldRanking;
    private String accreditation;
    private String instituteLogoUrl;
    private String averageCostFrom;
    private String averageCostTo;
    private String enrolment;
    private String tuitionFessPaymentPlan;
    private String scholarshipFinancingAssistance;
    private String email;
    private String phoneNumber;
    private String website;
    private String address;
    private Institute institute;

    public InstituteDetails() {
    }

    public InstituteDetails(String type, String youtubeLink, String ttionFeesPPlan, String courseStart, String openingHour, String closingHour, String enrolmentLink,
                    String aboutUsInfo, String climate2, String avgCostOfLiving, String whatsappNo, String englishPartners) {
        this.type = type;
        this.youtubeLink = youtubeLink;
        this.ttionFeesPPlan = ttionFeesPPlan;
        this.courseStart = courseStart;
        this.openingHour = openingHour;
        this.closingHour = closingHour;
        this.enrolmentLink = enrolmentLink;
        this.aboutUsInfo = aboutUsInfo;
        this.climate2 = climate2;
        this.avgCostOfLiving = avgCostOfLiving;
        this.whatsappNo = whatsappNo;
        this.englishPartners = englishPartners;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public BigInteger getInstituteId() {
        return this.instituteId;
    }

    public void setInstituteId(BigInteger instituteId) {
        this.instituteId = instituteId;
    }

    @Column(name = "type", length = 20)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "youtube_link", length = 2000)
    public String getYoutubeLink() {
        return this.youtubeLink;
    }

    public void setYoutubeLink(String youtubeLink) {
        this.youtubeLink = youtubeLink;
    }

    @Column(name = "ttion_fees_p_plan", length = 500)
    public String getTtionFeesPPlan() {
        return this.ttionFeesPPlan;
    }

    public void setTtionFeesPPlan(String ttionFeesPPlan) {
        this.ttionFeesPPlan = ttionFeesPPlan;
    }

    @Column(name = "course_start", length = 500)
    public String getCourseStart() {
        return this.courseStart;
    }

    public void setCourseStart(String courseStart) {
        this.courseStart = courseStart;
    }

    @Column(name = "opening_hour", length = 100)
    public String getOpeningHour() {
        return this.openingHour;
    }

    public void setOpeningHour(String openingHour) {
        this.openingHour = openingHour;
    }

    @Column(name = "closing_hour", length = 100)
    public String getClosingHour() {
        return this.closingHour;
    }

    public void setClosingHour(String closingHour) {
        this.closingHour = closingHour;
    }

    @Column(name = "enrolment_link", length = 500)
    public String getEnrolmentLink() {
        return this.enrolmentLink;
    }

    public void setEnrolmentLink(String enrolmentLink) {
        this.enrolmentLink = enrolmentLink;
    }

    @Column(name = "about_us_info", length = 500)
    public String getAboutUsInfo() {
        return this.aboutUsInfo;
    }

    public void setAboutUsInfo(String aboutUsInfo) {
        this.aboutUsInfo = aboutUsInfo;
    }

    @Column(name = "climate_2", length = 500)
    public String getClimate2() {
        return this.climate2;
    }

    public void setClimate2(String climate2) {
        this.climate2 = climate2;
    }

    @Column(name = "avg_cost_of_living", length = 500)
    public String getAvgCostOfLiving() {
        return this.avgCostOfLiving;
    }

    public void setAvgCostOfLiving(String avgCostOfLiving) {
        this.avgCostOfLiving = avgCostOfLiving;
    }

    @Column(name = "whatsapp_no", length = 500)
    public String getWhatsappNo() {
        return this.whatsappNo;
    }

    public void setWhatsappNo(String whatsappNo) {
        this.whatsappNo = whatsappNo;
    }

    @Column(name = "english_partners", length = 500)
    public String getEnglishPartners() {
        return this.englishPartners;
    }

    public void setEnglishPartners(String englishPartners) {
        this.englishPartners = englishPartners;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((aboutUsInfo == null) ? 0 : aboutUsInfo.hashCode());
        result = prime * result + ((avgCostOfLiving == null) ? 0 : avgCostOfLiving.hashCode());
        result = prime * result + ((climate2 == null) ? 0 : climate2.hashCode());
        result = prime * result + ((closingHour == null) ? 0 : closingHour.hashCode());
        result = prime * result + ((courseStart == null) ? 0 : courseStart.hashCode());
        result = prime * result + ((englishPartners == null) ? 0 : englishPartners.hashCode());
        result = prime * result + ((enrolmentLink == null) ? 0 : enrolmentLink.hashCode());
        result = prime * result + ((instituteId == null) ? 0 : instituteId.hashCode());
        result = prime * result + ((openingHour == null) ? 0 : openingHour.hashCode());
        result = prime * result + ((ttionFeesPPlan == null) ? 0 : ttionFeesPPlan.hashCode());
        result = prime * result + ((type == null) ? 0 : type.hashCode());
        result = prime * result + ((whatsappNo == null) ? 0 : whatsappNo.hashCode());
        result = prime * result + ((youtubeLink == null) ? 0 : youtubeLink.hashCode());
        return result;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        InstituteDetails other = (InstituteDetails) obj;
        if (aboutUsInfo == null) {
            if (other.aboutUsInfo != null)
                return false;
        } else if (!aboutUsInfo.equals(other.aboutUsInfo))
            return false;
        if (avgCostOfLiving == null) {
            if (other.avgCostOfLiving != null)
                return false;
        } else if (!avgCostOfLiving.equals(other.avgCostOfLiving))
            return false;
        if (climate2 == null) {
            if (other.climate2 != null)
                return false;
        } else if (!climate2.equals(other.climate2))
            return false;
        if (closingHour == null) {
            if (other.closingHour != null)
                return false;
        } else if (!closingHour.equals(other.closingHour))
            return false;
        if (courseStart == null) {
            if (other.courseStart != null)
                return false;
        } else if (!courseStart.equals(other.courseStart))
            return false;
        if (englishPartners == null) {
            if (other.englishPartners != null)
                return false;
        } else if (!englishPartners.equals(other.englishPartners))
            return false;
        if (enrolmentLink == null) {
            if (other.enrolmentLink != null)
                return false;
        } else if (!enrolmentLink.equals(other.enrolmentLink))
            return false;
        if (instituteId == null) {
            if (other.instituteId != null)
                return false;
        } else if (!instituteId.equals(other.instituteId))
            return false;
        if (openingHour == null) {
            if (other.openingHour != null)
                return false;
        } else if (!openingHour.equals(other.openingHour))
            return false;
        if (ttionFeesPPlan == null) {
            if (other.ttionFeesPPlan != null)
                return false;
        } else if (!ttionFeesPPlan.equals(other.ttionFeesPPlan))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        } else if (!type.equals(other.type))
            return false;
        if (whatsappNo == null) {
            if (other.whatsappNo != null)
                return false;
        } else if (!whatsappNo.equals(other.whatsappNo))
            return false;
        if (youtubeLink == null) {
            if (other.youtubeLink != null)
                return false;
        } else if (!youtubeLink.equals(other.youtubeLink))
            return false;
        return true;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("InstituteDetails [instituteId=").append(instituteId).append(", type=").append(type).append(", youtubeLink=").append(youtubeLink).append(", ttionFeesPPlan=")
                        .append(ttionFeesPPlan).append(", courseStart=").append(courseStart).append(", openingHour=").append(openingHour).append(", closingHour=")
                        .append(closingHour).append(", enrolmentLink=").append(enrolmentLink).append(", aboutUsInfo=").append(aboutUsInfo).append(", climate2=").append(climate2)
                        .append(", avgCostOfLiving=").append(avgCostOfLiving).append(", whatsappNo=").append(whatsappNo).append(", englishPartners=").append(englishPartners)
                        .append("]");
        return builder.toString();
    }

    /**
     * @return the latitute
     */
    @Column(name = "latitute")
    public String getLatitute() {
        return latitute;
    }

    /**
     * @param latitute
     *            the latitute to set
     */
    public void setLatitute(String latitute) {
        this.latitute = latitute;
    }

    /**
     * @return the longitude
     */
    @Column(name = "longitute")
    public String getLongitude() {
        return longitude;
    }

    /**
     * @param longitude
     *            the longitude to set
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * @return the totalStudent
     */
    @Column(name = "total_student")
    public Integer getTotalStudent() {
        return totalStudent;
    }

    /**
     * @param totalStudent
     *            the totalStudent to set
     */
    public void setTotalStudent(Integer totalStudent) {
        this.totalStudent = totalStudent;
    }

    /**
     * @return the worldRanking
     */
    @Column(name = "world_ranking")
    public Integer getWorldRanking() {
        return worldRanking;
    }

    /**
     * @param worldRanking
     *            the worldRanking to set
     */
    public void setWorldRanking(Integer worldRanking) {
        this.worldRanking = worldRanking;
    }

    /**
     * @return the accreditation
     */
    @Column(name = "accreditation")
    public String getAccreditation() {
        return accreditation;
    }

    /**
     * @param accreditation
     *            the accreditation to set
     */
    public void setAccreditation(String accreditation) {
        this.accreditation = accreditation;
    }

    /**
     * @return the instituteLogoUrl
     */
    @Column(name = "institute_logo_url")
    public String getInstituteLogoUrl() {
        return instituteLogoUrl;
    }

    /**
     * @param instituteLogoUrl
     *            the instituteLogoUrl to set
     */
    public void setInstituteLogoUrl(String instituteLogoUrl) {
        this.instituteLogoUrl = instituteLogoUrl;
    }

    /**
     * @return the averageCostFrom
     */
    @Column(name = "average_cost_from")
    public String getAverageCostFrom() {
        return averageCostFrom;
    }

    /**
     * @param averageCostFrom
     *            the averageCostFrom to set
     */
    public void setAverageCostFrom(String averageCostFrom) {
        this.averageCostFrom = averageCostFrom;
    }

    /**
     * @return the averageCostTo
     */
    @Column(name = "average_cost_to")
    public String getAverageCostTo() {
        return averageCostTo;
    }

    /**
     * @param averageCostTo
     *            the averageCostTo to set
     */
    public void setAverageCostTo(String averageCostTo) {
        this.averageCostTo = averageCostTo;
    }

    /**
     * @return the enrolment
     */
    @Column(name = "enrolment")
    public String getEnrolment() {
        return enrolment;
    }

    /**
     * @param enrolment
     *            the enrolment to set
     */
    public void setEnrolment(String enrolment) {
        this.enrolment = enrolment;
    }

    /**
     * @return the tuitionFessPaymentPlan
     */
    @Column(name = "tuition_fess_payment_plan")
    public String getTuitionFessPaymentPlan() {
        return tuitionFessPaymentPlan;
    }

    /**
     * @param tuitionFessPaymentPlan
     *            the tuitionFessPaymentPlan to set
     */
    public void setTuitionFessPaymentPlan(String tuitionFessPaymentPlan) {
        this.tuitionFessPaymentPlan = tuitionFessPaymentPlan;
    }

    /**
     * @return the scholarshipFinancingAssistance
     */
    @Column(name = "scholarship_financing_assistance")
    public String getScholarshipFinancingAssistance() {
        return scholarshipFinancingAssistance;
    }

    /**
     * @param scholarshipFinancingAssistance
     *            the scholarshipFinancingAssistance to set
     */
    public void setScholarshipFinancingAssistance(String scholarshipFinancingAssistance) {
        this.scholarshipFinancingAssistance = scholarshipFinancingAssistance;
    }

    /**
     * @return the email
     */
    @Column(name = "email")
    public String getEmail() {
        return email;
    }

    /**
     * @param email
     *            the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the phoneNumber
     */
    @Column(name = "phone_number")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @param phoneNumber
     *            the phoneNumber to set
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * @return the website
     */
    @Column(name = "website")
    public String getWebsite() {
        return website;
    }

    /**
     * @param website
     *            the website to set
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * @return the address
     */
    @Column(name = "address")
    public String getAddress() {
        return address;
    }

    /**
     * @param address
     *            the address to set
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * @return the institute
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "institute_id")
    public Institute getInstitute() {
        return institute;
    }

    /**
     * @param institute
     *            the institute to set
     */
    public void setInstitute(Institute institute) {
        this.institute = institute;
    }
}
