package com.seeka.app.bean;import java.math.BigInteger;

// Generated 7 Jun, 2019 2:45:49 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InstituteDetails generated by hbm2java
 */
@Entity
@Table(name = "institute_details", catalog = "seeka_dev_v5")
public class InstituteDetails implements java.io.Serializable {

	private BigInteger instituteId;
	private String type;
	private String youtubeLink;
	private String ttionFeesPPlan;
	private String courseStart;
	private String openingHour;
	private String closingHour;
	private String enrolmentLink;
	private String aboutUsInfo;
	private String climate2;
	private String avgCostOfLiving;
	private String whatsappNo;
	private String englishPartners;

	public InstituteDetails() {
	}

	public InstituteDetails(String type, String youtubeLink,
			String ttionFeesPPlan, String courseStart, String openingHour,
			String closingHour, String enrolmentLink, String aboutUsInfo,
			String climate2, String avgCostOfLiving, String whatsappNo,
			String englishPartners) {
		this.type = type;
		this.youtubeLink = youtubeLink;
		this.ttionFeesPPlan = ttionFeesPPlan;
		this.courseStart = courseStart;
		this.openingHour = openingHour;
		this.closingHour = closingHour;
		this.enrolmentLink = enrolmentLink;
		this.aboutUsInfo = aboutUsInfo;
		this.climate2 = climate2;
		this.avgCostOfLiving = avgCostOfLiving;
		this.whatsappNo = whatsappNo;
		this.englishPartners = englishPartners;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "institute_id", unique = true, nullable = false)
	public BigInteger getInstituteId() {
		return this.instituteId;
	}

	public void setInstituteId(BigInteger instituteId) {
		this.instituteId = instituteId;
	}

	@Column(name = "type", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "youtube_link", length = 2000)
	public String getYoutubeLink() {
		return this.youtubeLink;
	}

	public void setYoutubeLink(String youtubeLink) {
		this.youtubeLink = youtubeLink;
	}

	@Column(name = "ttion_fees_p_plan", length = 500)
	public String getTtionFeesPPlan() {
		return this.ttionFeesPPlan;
	}

	public void setTtionFeesPPlan(String ttionFeesPPlan) {
		this.ttionFeesPPlan = ttionFeesPPlan;
	}

	@Column(name = "course_start", length = 500)
	public String getCourseStart() {
		return this.courseStart;
	}

	public void setCourseStart(String courseStart) {
		this.courseStart = courseStart;
	}

	@Column(name = "opening_hour", length = 100)
	public String getOpeningHour() {
		return this.openingHour;
	}

	public void setOpeningHour(String openingHour) {
		this.openingHour = openingHour;
	}

	@Column(name = "closing_hour", length = 100)
	public String getClosingHour() {
		return this.closingHour;
	}

	public void setClosingHour(String closingHour) {
		this.closingHour = closingHour;
	}

	@Column(name = "enrolment_link", length = 500)
	public String getEnrolmentLink() {
		return this.enrolmentLink;
	}

	public void setEnrolmentLink(String enrolmentLink) {
		this.enrolmentLink = enrolmentLink;
	}

	@Column(name = "about_us_info", length = 500)
	public String getAboutUsInfo() {
		return this.aboutUsInfo;
	}

	public void setAboutUsInfo(String aboutUsInfo) {
		this.aboutUsInfo = aboutUsInfo;
	}

	@Column(name = "climate_2", length = 500)
	public String getClimate2() {
		return this.climate2;
	}

	public void setClimate2(String climate2) {
		this.climate2 = climate2;
	}

	@Column(name = "avg_cost_of_living", length = 500)
	public String getAvgCostOfLiving() {
		return this.avgCostOfLiving;
	}

	public void setAvgCostOfLiving(String avgCostOfLiving) {
		this.avgCostOfLiving = avgCostOfLiving;
	}

	@Column(name = "whatsapp_no", length = 500)
	public String getWhatsappNo() {
		return this.whatsappNo;
	}

	public void setWhatsappNo(String whatsappNo) {
		this.whatsappNo = whatsappNo;
	}

	@Column(name = "english_partners", length = 500)
	public String getEnglishPartners() {
		return this.englishPartners;
	}

	public void setEnglishPartners(String englishPartners) {
		this.englishPartners = englishPartners;
	}

}
