package com.seeka.app.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "institute_category_type")
public class InstituteCategoryType implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -7616230625430573849L;
    private String id;
    private String name;

    public InstituteCategoryType() {
    }

    public InstituteCategoryType(String name) {
        this.name = name;
    }

    @Id
    @GenericGenerator(name = "generator", strategy = "guid", parameters = {})
	@GeneratedValue(generator = "generator")
	@Column(name = "id", columnDefinition = "uniqueidentifier")
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "name", length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
