package com.seeka.app.bean;

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InstitueCampus generated by hbm2java
 */
@Entity
@Table(name = "institute_campus")
public class InstituteCampus {

    /**
     * 
     */
    private BigInteger id;
    private Institute institute;
    private String email;
    private String phoneNumber;
    private String address;
    private Double latitute;
    private Double longitute;
    private String openingFrom;
    private String openingTo;
    private String offerService;
    private Integer totalStudent;
    private Integer campusType;

    public InstituteCampus() {
        super();
    }

    public InstituteCampus(BigInteger id, BigInteger instituteId, String email, String phoneNumber, String address, Double latitute, Double longitute, String openingFrom,
                    String openingTo, String offerService, Integer totalStudent, Integer campus_type) {
        super();
        this.id = id;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.latitute = latitute;
        this.longitute = longitute;
        this.openingFrom = openingFrom;
        this.openingTo = openingTo;
        this.offerService = offerService;
        this.totalStudent = totalStudent;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public BigInteger getId() {
        return id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    @Column(name = "email")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "phone_number")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name = "address")
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "latitute")
    public Double getLatitute() {
        return latitute;
    }

    public void setLatitute(Double latitute) {
        this.latitute = latitute;
    }

    @Column(name = "longitute")
    public Double getLongitute() {
        return longitute;
    }

    public void setLongitute(Double longitute) {
        this.longitute = longitute;
    }

    @Column(name = "opening_from")
    public String getOpeningFrom() {
        return openingFrom;
    }

    public void setOpeningFrom(String openingFrom) {
        this.openingFrom = openingFrom;
    }

    @Column(name = "opening_to")
    public String getOpeningTo() {
        return openingTo;
    }

    public void setOpeningTo(String openingTo) {
        this.openingTo = openingTo;
    }

    @Column(name = "offer_service")
    public String getOfferService() {
        return offerService;
    }

    public void setOfferService(String offerService) {
        this.offerService = offerService;
    }

    @Column(name = "total_student")
    public Integer getTotalStudent() {
        return totalStudent;
    }

    public void setTotalStudent(Integer totalStudent) {
        this.totalStudent = totalStudent;
    }

    @Column(name = "campus_type")
    public Integer getCampusType() {
        return campusType;
    }

    public void setCampusType(Integer campusType) {
        this.campusType = campusType;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "institute_id")
    public Institute getInstitute() {
        return institute;
    }

    public void setInstitute(Institute institute) {
        this.institute = institute;
    }

}
