package com.seeka.app.bean;

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "institute_category_type")
public class InstituteCategoryType implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -7616230625430573849L;
    private BigInteger id;
    private String name;

    public InstituteCategoryType() {
    }

    public InstituteCategoryType(String name) {
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    @Column(name = "name", length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
