package com.seeka.app.bean;import java.math.BigInteger;

// Generated 7 Jun, 2019 2:45:49 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SearchKeywords generated by hbm2java
 */
@Entity
@Table(name = "search_keywords")
public class SearchKeywords implements java.io.Serializable {

	private BigInteger id;
	private String keyword;
	private String KDesc;

	public SearchKeywords() {
	}

	public SearchKeywords(String keyword, String KDesc) {
		this.keyword = keyword;
		this.KDesc = KDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public BigInteger getId() {
		return this.id;
	}

	public void setId(BigInteger id) {
		this.id = id;
	}

	@Column(name = "keyword", length = 250)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	@Column(name = "k_desc", length = 250)
	public String getKDesc() {
		return this.KDesc;
	}

	public void setKDesc(String KDesc) {
		this.KDesc = KDesc;
	}

}
