package com.seeka.app.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "seeka_subject")
public class Subject implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -4896547771928499529L;
    private String id;
    private String subjectName;
    private String educationSystemId;

    public Subject() {
    }

    public Subject(String subjectName, String educationSystemId) {
        this.subjectName = subjectName;
        this.educationSystemId = educationSystemId;
    }

    @Id
    @GenericGenerator(name = "generator", strategy = "guid", parameters = {})
	@GeneratedValue(generator = "generator")
	@Column(name = "id", columnDefinition = "uniqueidentifier")
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the subjectName
     */
    @Column(name = "subject_name", length = 55)
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * @param subjectName
     *            the subjectName to set
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    /**
     * @return the educationSystemId
     */
    @Column(name = "education_system_id")
    public String getEducationSystemId() {
        return educationSystemId;
    }

    /**
     * @param educationSystemId
     *            the educationSystemId to set
     */
    public void setEducationSystemId(String educationSystemId) {
        this.educationSystemId = educationSystemId;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((educationSystemId == null) ? 0 : educationSystemId.hashCode());
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((subjectName == null) ? 0 : subjectName.hashCode());
        return result;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Subject other = (Subject) obj;
        if (educationSystemId == null) {
            if (other.educationSystemId != null)
                return false;
        } else if (!educationSystemId.equals(other.educationSystemId))
            return false;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (subjectName == null) {
            if (other.subjectName != null)
                return false;
        } else if (!subjectName.equals(other.subjectName))
            return false;
        return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Subject [id=" + id + ", subjectName=" + subjectName + ", educationSystemId=" + educationSystemId + "]";
    }
}