package com.seeka.app.bean;

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigInteger;

// Generated 7 Jun, 2019 2:45:49 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * UserEducationDetails generated by hbm2java
 */
@Entity
@Table(name = "user_education_details", catalog = "seeka_dev_v5")
public class UserEducationDetails implements java.io.Serializable {

    private BigInteger userId;
    private BigInteger eduCountry;
    private BigInteger eduSystemId;
    private String eduInstitue;
    private String gpaScore;
    private String isEnglishMedium;
    private String englishLevel;
    private String eduSysScore;
    private String eduLevel;
    private Boolean isActive;
    private Date createdOn;
    private Date updatedOn;
    private Date deletedOn;
    private String createdBy;
    private String updatedBy;
    private Boolean isDeleted;

    private String educationSystemName;

    private String educationCountryName;

    public UserEducationDetails() {
    }

    public UserEducationDetails(BigInteger eduCountry, BigInteger eduSystemId, String eduInstitue, String gpaScore, String isEnglishMedium, String englishLevel, String eduSysScore,
                    String eduLevel, Boolean isActive, Date createdOn, Date updatedOn, Date deletedOn, String createdBy, String updatedBy, Boolean isDeleted) {
        this.eduCountry = eduCountry;
        this.eduSystemId = eduSystemId;
        this.eduInstitue = eduInstitue;
        this.gpaScore = gpaScore;
        this.isEnglishMedium = isEnglishMedium;
        this.englishLevel = englishLevel;
        this.eduSysScore = eduSysScore;
        this.eduLevel = eduLevel;
        this.isActive = isActive;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.deletedOn = deletedOn;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.isDeleted = isDeleted;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "user_id", unique = true, nullable = false)
    public BigInteger getUserId() {
        return this.userId;
    }

    public void setUserId(BigInteger userId) {
        this.userId = userId;
    }

    @Column(name = "edu_country")
    public BigInteger getEduCountry() {
        return this.eduCountry;
    }

    public void setEduCountry(BigInteger eduCountry) {
        this.eduCountry = eduCountry;
    }

    @Column(name = "edu_system_id")
    public BigInteger getEduSystemId() {
        return this.eduSystemId;
    }

    public void setEduSystemId(BigInteger eduSystemId) {
        this.eduSystemId = eduSystemId;
    }

    @Column(name = "edu_institue", length = 500)
    public String getEduInstitue() {
        return this.eduInstitue;
    }

    public void setEduInstitue(String eduInstitue) {
        this.eduInstitue = eduInstitue;
    }

    @Column(name = "gpa_score", length = 50)
    public String getGpaScore() {
        return this.gpaScore;
    }

    public void setGpaScore(String gpaScore) {
        this.gpaScore = gpaScore;
    }

    @Column(name = "is_english_medium", length = 10)
    public String getIsEnglishMedium() {
        return this.isEnglishMedium;
    }

    public void setIsEnglishMedium(String isEnglishMedium) {
        this.isEnglishMedium = isEnglishMedium;
    }

    @Column(name = "english_level", length = 100)
    public String getEnglishLevel() {
        return this.englishLevel;
    }

    public void setEnglishLevel(String englishLevel) {
        this.englishLevel = englishLevel;
    }

    @Column(name = "edu_sys_score", length = 100)
    public String getEduSysScore() {
        return this.eduSysScore;
    }

    public void setEduSysScore(String eduSysScore) {
        this.eduSysScore = eduSysScore;
    }

    @Column(name = "edu_level", length = 100)
    public String getEduLevel() {
        return this.eduLevel;
    }

    public void setEduLevel(String eduLevel) {
        this.eduLevel = eduLevel;
    }

    @Column(name = "is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", length = 19)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_on", length = 19)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "deleted_on", length = 19)
    public Date getDeletedOn() {
        return this.deletedOn;
    }

    public void setDeletedOn(Date deletedOn) {
        this.deletedOn = deletedOn;
    }

    @Column(name = "created_by", length = 50)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "updated_by", length = 50)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Column(name = "is_deleted")
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * @return the educationSystemName
     */
    @Transient
    public String getEducationSystemName() {
        return educationSystemName;
    }

    /**
     * @param educationSystemName
     *            the educationSystemName to set
     */
    public void setEducationSystemName(String educationSystemName) {
        this.educationSystemName = educationSystemName;
    }

    /**
     * @return the educationCountryName
     */
    @Transient
    public String getEducationCountryName() {
        return educationCountryName;
    }

    /**
     * @param educationCountryName
     *            the educationCountryName to set
     */
    public void setEducationCountryName(String educationCountryName) {
        this.educationCountryName = educationCountryName;
    }

}
